SELECT
    TO_NUMBER(NUMBER_INTEGRATION_ID) AS NUMBER_INTEGRATION_ID,
    EVENT_DATETIME,
    PARSE_JSON(OWNERSHIP):"costCenter"::VARCHAR  AS COST_CENTER,
    PARSE_JSON(OWNERSHIP):"ownerUserId"::VARCHAR AS USER_ID,
    STATUS_NAME                                  AS STATUS,
    INSTALLATION_CODE,
    INSTALLATION_DATE,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE
FROM {{ source('minerva', 'YUKON_OPPORTUNITY_INSTALLED_ES') }}
WHERE NUMBER_INTEGRATION_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NUMBER_INTEGRATION_ID
    ORDER BY EVENT_DATETIME DESC
) = 1
ORDER BY NUMBER_INTEGRATION_ID DESC