SELECT
    TO_NUMBER(NUMBER_INTEGRATION_ID) AS NUMBER_INTEGRATION_ID,
    OPPORTUNITY_NUMBER,
    OWNERSHIP_CHANNEL,
    OWNERSHIP_SUBCHANNEL,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE,
    DATE(END_CONSTRUCTION_DATE)                                                     AS END_CONSTRUCTION_DATE,
    CREATION_DATETIME,
    OPPORTUNITY_ID,
    UNIQUE_INTENDER_ID,
    STATUS_NAME,
    ACD_DESCRIPTION,
    CONVERT_TIMEZONE('UTC', 'Europe/Madrid', LEAD_GENERATION_DATETIME)             AS FEC_CREACION_PROSPECTO,
    PARSE_JSON(OWNERSHIP):"costCenter"::VARCHAR                                     AS COST_CENTER,
    PARSE_JSON(OWNERSHIP):"ownerUserId"::VARCHAR                                    AS ASSSIGNED_USER,
    EVENT_DATETIME
FROM {{ source('minerva', 'YUKON_OPPORTUNITY_CREATED_ES') }}
WHERE NUMBER_INTEGRATION_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NUMBER_INTEGRATION_ID
    ORDER BY EVENT_DATETIME DESC
) = 1
ORDER BY NUMBER_INTEGRATION_ID DESC