SELECT
    TO_NUMBER(NUMBER_INTEGRATION_ID) AS NUMBER_INTEGRATION_ID,
    OWNERSHIP_SUBCHANNEL,
    EVENT_DATETIME,
    PARSE_JSON(OWNERSHIP):"costCenter"::VARCHAR AS COST_CENTER,
    ASSSIGNED_USER,
    ALLOCATOR_USER,
    STATUS_NAME                                AS STATUS,
    SALES_BRANCH_INFO
FROM {{ source('minerva', 'YUKON_VISIT_ASSIGNED_ES') }}
WHERE NUMBER_INTEGRATION_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NUMBER_INTEGRATION_ID
    ORDER BY EVENT_DATETIME DESC
) = 1
ORDER BY NUMBER_INTEGRATION_ID DESC