SELECT
    TO_NUMBER(NUMBER_INTEGRATION_ID) AS NUMBER_INTEGRATION_ID,
    OPPORTUNITY_NUMBER,
    EVENT_DATETIME,
    PARSE_JSON(OWNERSHIP):"costCenter"::VARCHAR  AS COST_CENTER,
    PARSE_JSON(OWNERSHIP):"ownerUserId"::VARCHAR AS USER_ID,
    STATUS_NAME                                  AS STATUS,
    CHANGE_REASON                                AS CLOSING_REASON,
    CHANGE_TYPE                                  AS CLOSING_TYPE,
    EVENT_DATETIME                               AS CLOSING_DATE,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE
FROM {{ source('minerva', 'YUKON_OPPORTUNITY_CLOSED_ES') }}
WHERE NUMBER_INTEGRATION_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NUMBER_INTEGRATION_ID
    ORDER BY EVENT_DATETIME DESC
) = 1
ORDER BY NUMBER_INTEGRATION_ID DESC