SELECT
    TO_NUMBER(NUMBER_INTEGRATION_ID) AS NUMBER_INTEGRATION_ID,
    CREATION_DATETIME,
    EVENT_DATETIME,
    OWNERSHIP_CHANNEL,
    OWNERSHIP_SUBCHANNEL,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE,
    CONVERT_TIMEZONE('UTC', 'Europe/Madrid', VISIT_APPOINTMENT_DATE) AS VISIT_APPOINTMENT_DATE,
    DATE(END_CONSTRUCTION_DATE)                                       AS END_CONSTRUCTION_DATE,
    BOOKER_USER,
    OWNERSHIP,
    OPPORTUNITY_ID,
    OPPORTUNITY_NUMBER,
    UNIQUE_INTENDER_ID,
    STATUS_NAME
FROM {{ source('minerva', 'YUKON_VISIT_BOOKED_ES') }}
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY NUMBER_INTEGRATION_ID
    ORDER BY EVENT_DATETIME DESC
) = 1
ORDER BY NUMBER_INTEGRATION_ID DESC
