WITH

CLOSED_DUE_TO_OPP AS (
    SELECT DISTINCT
        CREATED.NUMBER_INTEGRATION_ID
    FROM {{ source('minerva', 'YUKON_OPPORTUNITY_CLOSED_ES') }} AS CLOSED
    INNER JOIN {{ source('minerva', 'YUKON_OPPORTUNITY_CREATED_ES') }} AS CREATED
        ON CLOSED.OPPORTUNITY_NUMBER = CREATED.OPPORTUNITY_NUMBER
    WHERE CLOSED.CHANGE_REASON LIKE '%Due to Opp%'
      AND CLOSED.NUMBER_INTEGRATION_ID IS NULL
      AND CREATED.NUMBER_INTEGRATION_ID IS NOT NULL
),

TLVANU_PROSPECTOS AS (
    SELECT DISTINCT NUMBER_INTEGRATION_ID
    FROM {{ source('minerva', 'YUKON_OPPORTUNITY_CREATED_ES') }}
    WHERE NUMBER_INTEGRATION_ID IS NOT NULL
      AND UPPER(PARSE_JSON(OWNERSHIP):"ownerUserId"::VARCHAR) = 'TLVANU'

    UNION

    SELECT DISTINCT NUMBER_INTEGRATION_ID
    FROM {{ source('minerva', 'YUKON_OFFER_SENT_ES') }}
    WHERE NUMBER_INTEGRATION_ID IS NOT NULL
      AND UPPER(PARSE_JSON(OWNERSHIP):"ownerUserId"::VARCHAR) = 'TLVANU'
),

FINAL AS (
    SELECT
        COALESCE(BOOKED.NUMBER_INTEGRATION_ID, CREATED.NUMBER_INTEGRATION_ID) AS ID_PROSPECTO,
        COALESCE(
            IFF(INSTALLED.NUMBER_INTEGRATION_ID IS NOT NULL, 'INSTALLED', NULL),
            IFF(OFFERSENT.NUMBER_INTEGRATION_ID IS NOT NULL, 'OFFERSENT', NULL),
            IFF(CLOSED.NUMBER_INTEGRATION_ID IS NOT NULL, 'CLOSED', NULL),
            IFF(ASSIGNED.NUMBER_INTEGRATION_ID IS NOT NULL, 'ASSIGNED', NULL),
            IFF(BOOKED.NUMBER_INTEGRATION_ID IS NOT NULL, 'BOOKED', NULL),
            IFF(UPDATED.NUMBER_INTEGRATION_ID IS NOT NULL, 'UPDATED', 'CREATED')
        )                                                                       AS PROSPECT_STATUS,
        CREATED.FEC_CREACION_PROSPECTO,
        COALESCE(BOOKED.CREATION_DATETIME, CREATED.CREATION_DATETIME)          AS SSFULTMODIFICA,
        COALESCE(BOOKED.OWNERSHIP_CHANNEL, CREATED.OWNERSHIP_CHANNEL)          AS OWNERSHIP_CHANNEL,
        COALESCE(CREATED.OWNERSHIP_SUBCHANNEL, BOOKED.OWNERSHIP_SUBCHANNEL)    AS OWNERSHIP_SUBCHANNEL,
        COALESCE(BOOKED.ZIP_CODE, CREATED.ZIP_CODE)                            AS ZIP_CODE,
        COALESCE(BOOKED.SEGMENT, CREATED.SEGMENT)                              AS SEGMENT,
        COALESCE(BOOKED.SEGMENT_SUBTYPE, CREATED.SEGMENT_SUBTYPE)              AS SEGMENT_SUBTYPE,
        BOOKED.VISIT_APPOINTMENT_DATE,
        COALESCE(BOOKED.END_CONSTRUCTION_DATE, CREATED.END_CONSTRUCTION_DATE)  AS END_CONSTRUCTION_DATE,
        INSTALLED.INSTALLATION_CODE,
        INSTALLED.INSTALLATION_DATE,
        COALESCE(BOOKED.BOOKER_USER, INSTALLED.USER_ID, CLOSED.USER_ID)        AS USER_ID,
        COALESCE(CREATED.ASSSIGNED_USER, ASSIGNED.ASSSIGNED_USER)              AS ASSSIGNED_USER,
        ASSIGNED.ALLOCATOR_USER,
        CASE
            WHEN COALESCE(ASSIGNED.COST_CENTER, UPDATED.COST_CENTER_RAW, CREATED.COST_CENTER) = '89'
                THEN UPDATED.COST_CENTER_PREV
            WHEN COALESCE(ASSIGNED.COST_CENTER, UPDATED.COST_CENTER_RAW, CREATED.COST_CENTER) = '892'
                AND (CLOSED_DUE_TO_OPP.NUMBER_INTEGRATION_ID IS NOT NULL
                     OR TLVANU_PROSPECTOS.NUMBER_INTEGRATION_ID IS NOT NULL)
                THEN UPDATED.COST_CENTER_PREV
            ELSE COALESCE(
                CASE WHEN OFFERSENT.COST_CENTER IN ('89','892') THEN NULL ELSE OFFERSENT.COST_CENTER END,
                IFF(UPDATED.COST_CENTER_RAW IN ('89','892'), UPDATED.COST_CENTER_PREV, UPDATED.COST_CENTER_RAW),
                INSTALLED.COST_CENTER,
                CLOSED.COST_CENTER,
                ASSIGNED.COST_CENTER,
                ASSIGNED.SALES_BRANCH_INFO,
                CREATED.COST_CENTER
            )
        END                                                                     AS COST_CENTER,
        COALESCE(BOOKED.OPPORTUNITY_ID, CREATED.OPPORTUNITY_ID)                AS OPPORTUNITY_ID,
        COALESCE(BOOKED.OPPORTUNITY_NUMBER, CREATED.OPPORTUNITY_NUMBER)        AS OPPORTUNITY_NUMBER,
        COALESCE(BOOKED.UNIQUE_INTENDER_ID, CREATED.UNIQUE_INTENDER_ID)        AS UNIQUE_INTENDER_ID,
        COALESCE(
            INSTALLED.STATUS,
            OFFERSENT.STATUS,
            CLOSED.STATUS,
            ASSIGNED.STATUS,
            BOOKED.STATUS_NAME,
            CREATED.STATUS_NAME
        )                                                                       AS STATUS_BOOKING,
        COALESCE(
            INSTALLED.INSTALLATION_DATE,
            CLOSED.CLOSING_DATE,
            ASSIGNED.EVENT_DATETIME,
            BOOKED.EVENT_DATETIME,
            CREATED.EVENT_DATETIME
        )                                                                       AS STATUS_DATE,
        CLOSED.CLOSING_REASON,
        CLOSED.CLOSING_TYPE,
        CREATED.ACD_DESCRIPTION,
        CASE
            WHEN STATUS_BOOKING = 'VISIT_BOOKED'   THEN 'VACEP'
            WHEN STATUS_BOOKING = 'SALES_FEEDBACK' THEN 'No Terminado'
            WHEN STATUS_BOOKING = 'VISIT_ASSIGNED' THEN 'VASIG'
            WHEN STATUS_BOOKING = 'INSTALLED'      THEN 'TERM-Instalada'
            WHEN STATUS_BOOKING = 'CLOSED'         THEN CONCAT('Closed-', CLOSING_REASON)
        END                                                                     AS STATUS_CRM41,
        CURRENT_DATE()                                                          AS LOAD_DATE
    FROM {{ ref('yukon_int_created') }}   AS CREATED
    LEFT JOIN {{ ref('yukon_int_booked') }}   AS BOOKED
        ON CREATED.NUMBER_INTEGRATION_ID = BOOKED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_assigned') }} AS ASSIGNED
        ON CREATED.NUMBER_INTEGRATION_ID = ASSIGNED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_installed') }} AS INSTALLED
        ON CREATED.NUMBER_INTEGRATION_ID = INSTALLED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_closed') }}   AS CLOSED
        ON CREATED.NUMBER_INTEGRATION_ID = CLOSED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_updated') }}  AS UPDATED
        ON CREATED.NUMBER_INTEGRATION_ID = UPDATED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_offersent') }} AS OFFERSENT
        ON CREATED.NUMBER_INTEGRATION_ID = OFFERSENT.NUMBER_INTEGRATION_ID
    LEFT JOIN CLOSED_DUE_TO_OPP
        ON CREATED.NUMBER_INTEGRATION_ID = CLOSED_DUE_TO_OPP.NUMBER_INTEGRATION_ID
    LEFT JOIN TLVANU_PROSPECTOS
        ON CREATED.NUMBER_INTEGRATION_ID = TLVANU_PROSPECTOS.NUMBER_INTEGRATION_ID
)

SELECT DISTINCT * FROM FINAL
WHERE FEC_CREACION_PROSPECTO IS NOT NULL
ORDER BY ID_PROSPECTO DESC