{{ config(
    materialized = 'incremental',
    incremental_strategy = 'merge',
    unique_key = 'ID_PROSPECTO'
) }}

WITH
BASE AS (

    SELECT
        COALESCE(BOOKED.NUMBER_INTEGRATION_ID, CREATED.NUMBER_INTEGRATION_ID) AS ID_PROSPECTO,
        COALESCE(
            IFF(INSTALLED.NUMBER_INTEGRATION_ID IS NOT NULL, 'INSTALLED', NULL),
            IFF(OFFERSENT.NUMBER_INTEGRATION_ID IS NOT NULL, 'OFFERSENT', NULL),
            IFF(CLOSED.NUMBER_INTEGRATION_ID IS NOT NULL, 'CLOSED', NULL),
            IFF(ASSIGNED.NUMBER_INTEGRATION_ID IS NOT NULL, 'ASSIGNED', NULL),
            IFF(BOOKED.NUMBER_INTEGRATION_ID IS NOT NULL, 'BOOKED', NULL),
            IFF(UPDATED.NUMBER_INTEGRATION_ID IS NOT NULL, 'UPDATED', 'CREATED')
        ) AS PROSPECT_STATUS,
        CREATED.FEC_CREACION_PROSPECTO,
        COALESCE(BOOKED.CREATION_DATETIME, CREATED.CREATION_DATETIME) AS SSFULTMODIFICA,
        CURRENT_DATE() AS LOAD_DATE,
        CREATED.EVENT_DATETIME AS STATUS_DATE,
        CREATED.OPPORTUNITY_NUMBER
        -- añade aquí el resto de columnas que necesites
    FROM {{ ref('yukon_int_created') }} CREATED
    LEFT JOIN {{ ref('yukon_int_booked') }} BOOKED
        ON CREATED.NUMBER_INTEGRATION_ID = BOOKED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_assigned') }} ASSIGNED
        ON CREATED.NUMBER_INTEGRATION_ID = ASSIGNED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_installed') }} INSTALLED
        ON CREATED.NUMBER_INTEGRATION_ID = INSTALLED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_closed') }} CLOSED
        ON CREATED.NUMBER_INTEGRATION_ID = CLOSED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_updated') }} UPDATED
        ON CREATED.NUMBER_INTEGRATION_ID = UPDATED.NUMBER_INTEGRATION_ID
    LEFT JOIN {{ ref('yukon_int_offersent') }} OFFERSENT
        ON CREATED.NUMBER_INTEGRATION_ID = OFFERSENT.NUMBER_INTEGRATION_ID

    {% if is_incremental() %}
      WHERE COALESCE(BOOKED.CREATION_DATETIME, CREATED.CREATION_DATETIME)
            >= (SELECT MAX(SSFULTMODIFICA) FROM {{ this }})
    {% endif %}
),
RANKED AS (

    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY ID_PROSPECTO
            ORDER BY
                SSFULTMODIFICA DESC,
                CASE PROSPECT_STATUS
                    WHEN 'INSTALLED' THEN 6
                    WHEN 'BOOKED'    THEN 5
                    WHEN 'CLOSED'    THEN 4
                    WHEN 'ASSIGNED'  THEN 3
                    WHEN 'UPDATED'   THEN 2
                    WHEN 'CREATED'   THEN 1
                    ELSE 0
                END DESC,
                LOAD_DATE DESC
        ) AS RN
    FROM BASE
)
SELECT
    *
FROM RANKED
QUALIFY RN = 1
ORDER BY ID_PROSPECTO DESC