SELECT
    ID_PROSPECTO,
    PROSPECT_STATUS,
    OPPORTUNITY_NUMBER,
    FEC_CREACION_PROSPECTO,
    SSFULTMODIFICA,
    OWNERSHIP_CHANNEL,
    OWNERSHIP_SUBCHANNEL,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE,
    VISIT_APPOINTMENT_DATE,
    END_CONSTRUCTION_DATE,
    USER_ID,
    ASSSIGNED_USER,
    ALLOCATOR_USER,
    COST_CENTER,
    OPPORTUNITY_ID,
    UNIQUE_INTENDER_ID,
    STATUS_BOOKING,
    STATUS_CRM41,
    INSTALLATION_CODE,
    LOAD_DATE
FROM {{ ref('fact_mktv_visitas') }}
WHERE OWNERSHIP_SUBCHANNEL = 'Telebooking'
  AND UPPER(USER_ID) NOT IN ('CAIXA')
ORDER BY ID_PROSPECTO DESC