SELECT
    ID_PROSPECTO,
    INSTALLATION_CODE,
    PROSPECT_STATUS,
    OPPORTUNITY_NUMBER,
    FEC_CREACION_PROSPECTO,
    SSFULTMODIFICA,
    OWNERSHIP_CHANNEL,
    OWNERSHIP_SUBCHANNEL,
    ZIP_CODE,
    SEGMENT,
    SEGMENT_SUBTYPE,
    VISIT_APPOINTMENT_DATE,
    END_CONSTRUCTION_DATE,
    USER_ID_VS,
    ASSSIGNED_USER,
    ALLOCATOR_USER,
    COST_CENTER,
    OPPORTUNITY_ID,
    UNIQUE_INTENDER_ID,
    STATUS_BOOKING,
    STATUS_CRM41,
    STATUS_DATE,
    LOAD_DATE
FROM {{ ref('fact_mktv_visitas') }}
WHERE (ASSSIGNED_USER LIKE 'TLC%' OR ASSSIGNED_USER LIKE 'TELEC%')
  AND PROSPECT_STATUS = 'INSTALLED'
ORDER BY ID_PROSPECTO DESC