SELECT
    OPPORTUNITY_NUMBER,
    ID_PROSPECTO,
    SSFULTMODIFICA,
    FEC_CREACION_PROSPECTO,
    INSTALLATION_CODE,
    ACD_DESCRIPTION,
    IFF(PROSPECT_STATUS = 'CLOSED', CLOSING_REASON, PROSPECT_STATUS) AS PROSPECT_STATUS,
    COST_CENTER,
    ZIP_CODE,
    OWNERSHIP_CHANNEL,
    OWNERSHIP_SUBCHANNEL,
    SEGMENT,
    SEGMENT_SUBTYPE,
    END_CONSTRUCTION_DATE,
    USER_ID,
    ASSSIGNED_USER,
    OPPORTUNITY_ID,
    UNIQUE_INTENDER_ID,
    STATUS_BOOKING,
    STATUS_CRM41,
    STATUS_DATE,
    LOAD_DATE
FROM {{ ref('fact_mktv_visitas') }}
WHERE OWNERSHIP_SUBCHANNEL = 'Telesales'
ORDER BY ID_PROSPECTO DESC